### ISSUE TITLE
What is the point?

### ISSUE THREAD

**Issue by mvila** [jlipps/mochawait#3]
Actually, I am not sure to understand the point of this module... Since async functions return promises and mocha supports them, async/await works without having to do anything special!

For example...

``` javascript
describe('collection', function() {
  it('should return an item', async function() {
    let item = await collection.get('xyz');
    assert(item.id === 'xyz');
  });
});
```

... just works!

Do I miss something?

**Comment by henryboldi** [comment]
+1

**Comment by jlipps** [comment]
looks like they added support for promises at some point since I started caring about this. So this module is no longer necessary!

**Comment by jlipps** [comment]
updated the readme
